config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # マイページ
  resources :users, only: [:show]

  root to: 'notes#index'

  # 新着順(投稿)を取得
  get 'notes/order_index', to: 'notes#order_index'

  # いいねしてくれたユーザーを表示するためのルーティング
  get 'favorites/user/:id', to: 'favorites#user'

  # コメントした投稿を表示するためのルーティング
  get 'comments/user/:id', to: 'comments#user'

  # いいねした投稿を表示するためのルーティング
  get 'notes/favorite/:id', to: 'notes#favorite'

  # フォローしているユーザー一覧のルーティング
  get 'followings/user/:id', to: 'relationships#followings'

  # フォロワー一覧のルーティング
  get 'followers/user/:id', to: 'relationships#followers'

  # タグがつけられた投稿一覧のルーティング
  get 'tag/:id/notes', to: 'tags#note'

  # ユーザーのメモページへのルーティング
  get 'memos/user/:id', to: 'memos#index'

  # メモ既読機能
  get 'memos/:id', to: 'memos#checked'

  resources :memos, only: %i[create destroy]

  # プロフィール編集ページ
  resources :intros, only: %i[new create edit update]

  # 投稿(いいね・コメント),インクリメンタルサーチ
  resources :notes do
    resources :favorites, only: %i[create destroy]
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
    collection do
      get 'note_search'
    end
  end

  # コメント削除機能のルーティング
  resources :comments, only: [:destroy]

  # フォロー機能のルーティング
  resources :relationships, only: %i[create destroy]

  # 通知機能のルーティング
  resources :notifications, only: %i[index destroy]

  # DM機能のルーティング
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show destroy]
end

app/models/note.rb
class Note < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :text
    validates :plan
  end

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :note_tags, dependent: :destroy
  has_many :tags, through: :note_tags, dependent: :destroy

  # コメントした投稿を取得するための記述
  has_many :commented_users, through: :comments, source: :user

  has_many :favorites, dependent: :destroy

  # いいねした投稿を取得するための記述
  has_many :favorited_users, through: :favorites, source: :user

  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      note_id: id,
      visited_id: user_id,
      action: 'favorite'
    )
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(note_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end

    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、1つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      note_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメント場合は、通知済みとする
    notification.checked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end

  def self.search(search)
    if search != ''
      Note.where('text LIKE(?)', "%#{search}%")
    else
      Note.all
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, except: %i[index order_index show search]
  before_action :set_note, only: %i[show edit update destroy favorite]

  def index
    @notes = Note.includes(:user).sort { |a, b| b.favorited_users.count <=> a.favorited_users.count }
    @notes = Kaminari.paginate_array(@notes).page(params[:page]).per(6)
  end

  def order_index
    @notes = Note.includes(:user).page(params[:page]).per(6).order('created_at DESC')
  end

  def new
    @note = NoteTagRelation.new
  end

  def create
    @note = NoteTagRelation.new(note_tag_params)
    if @note.valid?
      @note.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @note.comments.includes(:user).order('created_at DESC')
  end

  def edit
    redirect_to note_path(@note.id) unless @note.user_id == current_user.id
  end

  def update
    if @note.update(note_params)
      redirect_to note_path(@note.id)
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @note.user_id
      @note.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def favorite
  end

  def search
    return nil if params[:keyword] == ''

    tag = Tag.where(['name LIKE ?', "%#{params[:keyword]}%"])
    render json: { keyword: tag }
  end

  def note_search
    @notes = Note.search(params[:keyword])
    @notes = @notes.page(params[:page]).per(10)
  end

  private

  def note_tag_params
    params.require(:note_tag_relation).permit(:title, :text, :plan, :image, :name).merge(user_id: current_user.id)
  end

  def note_params
    params.require(:note).permit(:title, :text, :plan, :image).merge(user_id: current_user.id)
  end

  def set_note
    @note = Note.find(params[:id])
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_header.html.erb
<% if user_signed_in? %>
    <%= render 'shared/note_header' %>
<% else %>
  <header>  
    <div class="upper-header">
      <div class="upper-left">
        <%= render 'shared/session_header' %>
      </div>
      <div class="upper-right">
        <%= link_to "ユーザー登録", new_user_registration_path, class: "upper-regist" %>
        <%= link_to "ログイン", new_user_session_path, class: "upper-session" %>
         <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "guest-session" %>
      </div>
    </div>
    <div class="lower-header">
      <div class="lower-left">
        <h2 class="catch-copy">Tell me your plan.</h2>
        <p class="explain">Plans Appは本や論文に関する知識を記録・共有するためのサービスです。<br>
        あなたのアクションプランを共有しましょう！</p>
      </div>
      <div class="lower-right">
        <div class="sns-session">
          <p class="sns-login">SNSで登録＆ログイン</p>
          <%= link_to user_twitter_omniauth_authorize_path, method: :post, class: "twitter-session" do %>
            <i class="fab fa-twitter twitter-icon"></i>Twitter
          <% end %>
          <%= link_to user_facebook_omniauth_authorize_path, method: :post, class: "facebook-session" do %>
            <i class="fab fa-facebook-square facebook-icon"></i>Facebook
          <% end %>
        </div>
        </div>
    </div>
  </header>
<% end %>

app/views/notes/_notes.html.erb
<div class="note-user">
<% if user_signed_in? %>
  <%= link_to user_path(notes.user.id) do %>
    <% if notes.user.intro.present? %>
      <div class="session-usericon">
        <%= image_tag notes.user.intro.image, class: "user-icon", alt: "ユーザーアイコン" %>
      </div> 
    <% else %>
      <div class="session-usericon">
        <img src="/assets/default.png" class="user-icon" alt="ユーザーアイコン">
      </div>
    <% end %>
  <% end %>
  <%= link_to notes.user.nickname, user_path(notes.user.id), class: "user-id" %>
  <div class="created-at">
    が<%= notes.created_at.to_s(:datetime_jp) %>に投稿
  </div>
<% end %>
</div>
<%= link_to note_path(notes.id), class: "note_show_links" do %>
  <div class="note-title">
    <h3><%= notes.title %></h3>
  </div>
  <% end %>
  <% notes.tags.each do |tag| %>
    <div class="note-tag">
      <i class="fas fa-tags tag-img"></i>
      <%= link_to "#{tag.name}", "/tag/#{tag.id}/notes", class: "tag" %>
    </div>
  <% end %>
<div class="note-options">
  <div class="note-opt">
    <div class="note-option-icon">
      <div class="favorite">
        <i class="fas fa-book like-btn"></i><span class="favorite-count"><%= notes.favorites.count %></span>
      </div>
      <div class="comment-num">
        <i class="far fa-comment comment-btn"></i><span class="comment-count"><%= notes.comments.count %></span>
      </div>
    </div>
  </div>
</div>

app/views/notes/_search.html.erb
<div class="search-form">
  <%= form_with(url: note_search_notes_path, local: true, method: :get) do |f| %>
    <%= f.text_field :keyword, placeholder: "キーワードを入力", class: "search-input" %>
    <%= f.submit "検索" , class: "search-btn"%>
  <% end %>
</div>
<div class="notes">
  <div class="note-order">
    <div class="feed">
      <p class="feed-title"><b>記事フィード</b></p>
      <%= link_to root_path, class: "trend" do %>
        <i class="fas fa-fire fire-icon"></i>トレンド
      <% end %>
      <%= link_to notes_order_index_path, class: "asc" do %>
        <i class="fas fa-sort-numeric-down asc-icon"></i>新着順
      <% end %>
    </div>
  <div>

app/views/notes/edit.html.erb
<div class="wrapper">
  <%= render 'shared/note_header' %>
  <div class="note-container">
    <div class="new-content">
      <%= form_with(model: @note, class: 'note_form', local: true) do |f| %>
        <div class="caption-area">
          <div class="title-box">
            <%= f.text_field :title, class: "input-title", placeholder: "タイトル", maxlength: 50, autofocus: true %>
          </div>
          <div class="note-new-opt">
            <i class="far fa-image note-img"><%= f.file_field :image, class: "input-note-image" %></i>
          </div>
        </div>
        <div class="note-editor">
          <div class="note-area-left">
            <%= f.text_area :text, class: "input-text", placeholder: "テキストを入力" %>
            <%= f.text_area :plan, class: "input-plan", placeholder: "アクションプランを共有しよう" %>
          </div>
          <div class="note-area-right">
            <div class="note-preview">
              <textarea type="text" calss="input-preview" placeholder="プレビュー機能実装予定" ></textarea>
            </div>
            <div class="note-submit">
              <%= f.submit 'Plansを投稿', class: "plan-btn" %>
              <div class="plan-drop">
                <a class="nav-link" href="#" id="navbarPlanDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-caret-up"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#"><i class="fas fa-clipboard save"></i>下書き保存</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#"><i class="fas fa-upload upload"></i>Plansを投稿</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/favorite.html.erb
<div class="wrapper">
  <div class="session-header">
    <%= render 'shared/session_header' %>
      <div class="session-right">
        <% if user_signed_in? %>
          <%= render 'shared/header_links' %>
        <% end %>
        <%= link_to user_path(current_user.id), class: 'upper-usericon' do %>
          <% if current_user.intro.present? %>
            <div class="session-usericon">
              <%= image_tag current_user.intro.image, class: "index-icon", alt: "ユーザーアイコン" %>
              </div> 
            <% else %> 
            <div class="session-usericon">
              <img src="/assets/default.png" class="index-icon" alt="ユーザーアイコン" >
            </div>
          <% end %> 
        <% end %>
      </div>
    </div>
  </div>
  <div class="detail-page-wrapper">
    <div class="favpage-main">
      <div class="top-left-content">
        <div class="likes-page-list-nav">
          <p><b><%= @note.title %></b></p>
          LIKEしたユーザー
        </div>
        <div class="item-pagenate">
          <% @note.favorited_users.order('created_at DESC').each do |user| %>
            <li class="item-list">
              <div class="favpage-user-info">
                <%= link_to user_path(user.id) do %>
                  <% if user.intro.present? %>
                    <%= image_tag user.intro.image, class: "user-icon", alt: "ユーザーアイコン" %>
                  <% else %>
                    <img src="/assets/default.png" class="user-icon" alt="ユーザーアイコン">
                  <% end %>
                <% end %>
                <div class="likes-user-nickname">
                  <%= link_to user.nickname, user_path(user.id), class: "likes-user-page-nickname-link" %>
                </div>
              </div>
              <div class="likes-user-profile">
                <span class="likes-user-profile-btn">Profile</span>
                <% if user.intro.present? %>
                  <p><%= user.intro.profile %></p>
                <% end %>
              </div>
              <div class="likes-user-opt">
                <div class="likes-user-icons">
                  <i class="fas fa-clipboard"></i><span><%= user.notes.count %></span>
                  <i class="fas fa-book myitem-like-btn"></i><span><%= user.favorites.count %></span>
                  <i class="far fa-comment myitem-comment-btn"></i><span><%= user.comments.count %></span>
                </div>
                <div class="likes-user-regist-day">
                  <%= user.created_at.strftime('%Y/%m/%d')%>から利用開始
                </div>
              </div>
            </li>
          <% end %>
        </div>
      </div>
      <div class="top-right-content">
        <div class="top-user-card">
          <div class="detail-page-user-card">
            <%= link_to user_path(@note.user.id), class: 'upper-usericon' do %>
              <% if @note.user.intro.present? %>
                <%= image_tag @note.user.intro.image, class: "detail-user-page-icon", alt: "ユーザーアイコン" %>
              <% else %>
                <img src="/assets/default.png" class="detail-user-page-icon " alt="ユーザーアイコン" >
              <% end %>
            <% end %>
          </div>
          <div class="detail-page-user-name">
            <% if @note.user.intro.present? %>
              <div class="detail-user-name">
                <p class="detail-user-firstname"><%= @note.user.intro.first_name%></p>
                <p class="detail-user-lastname"><%= @note.user.intro.last_name%></p>
              </div>
            <% else %>
              <div class="detail-user-nickname">
                <%= @note.user.nickname %>
              </div>
            <% end %>
          </div>
          <div class="user-status">
            <div class="user-status-top">
              <div class="user-status-note">
                <%= link_to '投稿', user_path(@note.user.id), class: "status" %>
                <span><%= @note.user.notes.count %></span>
                  </div>
              <div class="user-status-fav">
                <%= link_to "いいね", "/favorites/user/#{@note.user.id}", class: "status" %>
                <span><%= @note.user.favorites.count %></span>
              </div>
              <div class="user-status-comment">
                <%= link_to "コメント", "/comments/user/#{@note.user.id}", class: "status" %>
                <span><%= @note.comments.count %></span>
              </div>
            </div>
            <div class="user-status-bottom">
              <div class="user-status-follow">
                <%= link_to 'フォロー', "/followings/user/#{@note.user.id}", class: "status" %>
                <span><%= @note.user.followings.count %></span>
              </div>
              <div class="user-status-follower">
                <%= link_to 'フォロワー', "/followers/user/#{@note.user.id}", class: "status" %>
                <span><%= @note.user.followers.count %></span>
              </div>
            </div>
          </div>
        </div>
        <div class="detail-page-user-notes">
          <div class="item-list-navi">
            <i class="fas fa-square item-list-squere"></i><b><%= @note.user.nickname %></b>'s NOTES
          </div>
          <% @note.user.notes.each do |note| %>
            <li class="my-item-list">
              <div class="my-item-list-content">
                <div class="my-item-list-tag">
                  <i class="fas fa-tags my-list-tag-img"></i>
                  <a href="#" class="my-lst-tag">睡眠</a>
                  <a href ="#" class="my-list-tag">生産性</a>
                </div>
                <div class="my-item-list-detail">
                  <%= link_to note_path(note.id), class: "my_list_note_link" do %>
                    <%= note.title%>
                  <% end %>
                </div>
              </div>
              <div class="my-item-list-rower">
                <div class="my-item-list-opt">
                  <i class="fas fa-book myitem-like-btn"></i><span><%= note.favorites.count %></span>
                  <i class="far fa-comment myitem-comment-btn"></i><span><%= note.comments.count %></span>
                </div>
              </div>
              <div class="my-item-list-created">
                <%= note.created_at.strftime('%Y/%m/%d') %>
              </div>
            </li>
          <% end %>
        </div>
        <div class="my-detail-page-nation">
          <span>1/1</span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<div class="wrqpper">
  <%= render 'header' %>
  <main>
    <%= render 'search' %>
    <div class="notes">
      <div class="notes-trend">
        <p class="note-fire"><i class="fas fa-fire trend-fire"></i>トレンド</p>
          <%= render partial: 'notes', collection: @notes %>
        <div class="more-note">
          <%= paginate @notes %>
        </div>
      </div>
    </div>
  </main>
  <footer>
    <div class="footer">
      <%= render 'shared/footer' %>
    </div>
  </footer>
</div>

app/views/notes/new.html.erb
<div class="wrapper">
  <%= render 'shared/note_header' %>
  <div class="note-container">
    <div class="new-content">
      <%= form_with model: @note, url: notes_path, method: :post, class: 'note_form', local: true do |f| %>
        <div class="caption-area">
          <div class="title-box">
            <%= f.text_field :title, class: "input-title", placeholder: "タイトル", maxlength: 50, autofocus: true %>
          </div>
          <div class="note-new-opt">
            <span class="note-img">
              <i class="far fa-image"></i><%= f.file_field :image, class: "input-note-image" %>
            </span>
          </div>
        </div>
        <div class="new-right-note-rule">
            <a class="new-right-note-rule-link" href= 'https://www.plans30.com/notes/2'>投稿するにあたって</a>
          </div>
        <div class="note-editor">
          <div class="note-area-left">
            <%= f.text_area :text, class: "input-text", placeholder: "テキストを入力" %>
            <%= f.text_area :plan, class: "input-plan", placeholder: "アクションプランを共有しよう" %>
            <div class="tag-box", id="tag-field">
              <%= f.text_field :name, class: "input-tag", placeholder: "例： #心理学 #メンタルヘルス" %>
            </div>
            <div id="search-result">
            </div>
          </div>
          <div class="note-area-right">
            <div class="note-preview">
              <textarea type="text" calss="input-preview" placeholder="プレビュー機能実装予定" ></textarea>
            </div>
            <div class="note-submit">
              <%= f.submit 'Plansを投稿', class: "plan-btn" %>
              <div class="plan-drop">
                <a class="nav-link" href="#" id="navbarPlanDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-caret-up"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#"><i class="fas fa-clipboard save"></i>下書き保存</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#"><i class="fas fa-upload upload"></i>Plansを投稿</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="wrqpper">
  <% if user_signed_in? %>
    <%= render 'shared/note_header' %>
  <% else %>
    <div class="show-header">  
      <div class="upper-header">
        <div class="upper-left">
          <%= link_to "Plans App", root_path %>
        </div>
        <div class="upper-right">
          <%= link_to "ユーザー登録", new_user_registration_path, class: "upper-regist" %>
          <%= link_to "ログイン", new_user_session_path, class: "upper-session" %>
          <%= link_to 'ゲストログイン（閲覧用）',  users_guest_sigin_in_path, method: :post, class: "guest-session" %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="show-wrapper">
    <div class="show-main">
      <div class="show-top">
        <div class="show-top-info">
          <div class="show-top-profile">
          <% if user_signed_in? %>
            <%= link_to user_path(@note.user.id) do %>
              <% if @note.user.intro.present? %>
                <%= image_tag @note.user.intro.image, class: "show-top-icon", alt: "ユーザーアイコン" %>
              <% else %>
                <img src="/assets/default.png" class="show-top-icon" alt="ユーザーアイコン">
              <% end %>
            <% end %>
            <%= link_to @note.user.nickname, user_path(@note.user.id), class:'show-top-username' %>
          <% end %>
          </div>
          <% if user_signed_in? && @note.user_id == current_user.id%>
            <div class="show-top-command">
              <div class="plan-drop">
                <a class="nav-link" href="#" id="navbarPlanDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-cog"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to edit_note_path(@note.id), class:'dropdown-item' do %>
                    <i class="fas fa-clipboard save"></i>編集する
                  <% end %>
                  <div class="dropdown-divider"></div>
                  <%= link_to note_path(@note.id), method: :delete, class: 'dropdown-item' do %>
                    <i class="fas fa-upload upload"></i>削除する
                  <% end %>
                </div>
              </div>
            </div> 
          <% end %>
        </div>
        <span class="show-top-created"><%= @note.created_at.strftime('%Y年%m月%d日') %>に更新</span>
        <div class="show-top-caption">
          <div class="show-top-title">
            <%= @note.title %>
          </div>
          <div class="show-top-tags">
            <div class="show-top-tag">
              <% @note.tags.each do |tag| %>
                <i class="fas fa-tags tag-show-note-img"></i>
                <%= link_to "#{tag.name}", "/tag/#{tag.id}/notes", class: "tag" %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="show-top-communication">
          <div class="show-top-communication-left">
              <% if user_signed_in? %>
                <% if current_user.favorites.find_by(note_id: @note.id) %>
                  <%= link_to note_favorite_path(@note), method: :delete, class: "unfavorite", id: "unfavorite" do %>
                    <div class="show-top-nolike-btn">
                      <span><i class="fas fa-book"></i>LIKED</span>
                      <%= @note.favorites.count %>
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to note_favorites_path(@note), method: :post, class: "favorite", id: "favorite" do %>
                    <div class="show-top-like-btn">
                      <span><i class="fas fa-book"></i>LIKE</span>
                      <%= @note.favorites.count %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
          </div>
          <div class="show-top-communication-right">
            <%= link_to  "https://twitter.com/intent/tweet?text=タイトル:#{@note.title}#{request.url}", title: 'Twitter', target: '_blank', class: "show-top-twitter-btn" do %>
              <i class="fab fa-twitter show-top-twitter"></i>Twitter
            <% end %>
            <a href="http://line.me/R/msg/text/?{message}" class="show-top-line-btn"><i class="fab fa-line top-line show-top-line"></i>LINE</a>
          </div>
        </div>
        <div class="show-top-communication-after">
          <%= link_to 'LIKEしたユーザーを見る', "/notes/favorite/#{@note.id}" %>
        </div>
      </div>
      <div class="show-body">
        <p><%= markdown(@note.text).html_safe %></p>
      </div>
      <div class="show-body-note-image">
        <%= image_tag @note.image, class:"show-note-image", alt: "投稿した画像" if @note.image.attached? %>
      </div>
      <div class="show-body-plans">
        <h3>Action Plan</h3>
        <p class="show-body-plan"><%= markdown(@note.plan).html_safe %></p>
      </div>
      <div class="show-bottom">
        <div class="show-bottom-first">
          <%= link_to  "https://twitter.com/intent/tweet?text=タイトル:#{@note.title}#{request.url}", title: 'Twitter', target: '_blank', class: "show-share-twitter" do %>
            <i class="fab fa-twitter share-twitter"></i>
          <% end %>
          <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore"><i class="fab fa-facebook share-facebook"></i></a>
          <a href="http://line.me/R/msg/text/?{message}"><i class="fab fa-line share-line"></i></a>
        </div>
      </div>
      <div class="comment-area">
        <div class="comment-content">
          <% @comments.each do |comment| %>
            <div class="comment-btn-box">
              <div class="comment-btn-box-left">
              <% if user_signed_in? %>
                <%= link_to user_path(comment.user.id) do %>
                  <% if comment.user.intro.present? %>
                    <%= image_tag comment.user.intro.image, class: "show-top-icon", alt: "ユーザーアイコン" %>
                  <% else %>
                    <img src="/assets/default.png" class="show-top-icon" alt="ユーザーアイコン">
                  <% end %>
                <% end %>
                <%= link_to comment.user.nickname, user_path(comment.user.id), class: "show-top-username" %>
              <% end %>
              </div>
              <div class="comment-btn-box-right">
                <%= comment.created_at.strftime('%Y-%m-%d %H:%M')%>
                <% if user_signed_in? %>
                  <div class="comment-drop">
                    <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-h"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="#">このコメントを報告</a>
                      <% if current_user.id == comment.user_id %>
                        <div class="dropdown-divider"></div>
                        <%= link_to '削除する', comment_path(comment.id), method: :delete, class: "dropdown-item" %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="commnet-message">
              <p><%= comment.text %></p>
            </div>
            <div class="commnets-message-image">
              <p><%= image_tag comment.image, class: "comment-message-image", alt: "コメント画像" if comment.image.attached? %></p>
            </div>
          <% end %>
          <div class="comment-bottom-border-box">
            <div class="comment-bottom-border"></div>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="commnet-info">
            <%= link_to user_path(@note.user.id) do %>
              <% if current_user.intro.present? %>
                <%= image_tag current_user.intro.image, class: "user-icon", alt: "ユーザーアイコン" %>
              <% else %>
                <img src="/assets/default.png" class="user-icon" alt="ユーザーアイコン">
              <% end %>
            <% end %>
            <span class="commnet-new">投稿する</span>
          </div>
          <div class="comment-input">
            <div class="comment-menu">
            </div>
            <%= form_with(model: [@note, @comment], local: true) do |f| %>
              <div class="comment-form">
                <%= f.text_area :text, placeholder: "テキストを入力", class: "comment-textarea" %>
              </div>
              <div class="comment-opt">
                <div class="comment-opt-image">
                  <span class="comment-image">
                    <i class="far fa-image comment-img-icon"></i>
                    画像を選択 <%= f.file_field :image,class: "comment-img-input" %>
                  </span>
                </div>
                <%= f.submit "投稿", class: "comment-submit", id: "comment_submit" %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>