config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # マイページ
  resources :users, only: [:show]

  root to: 'notes#index'

  # 新着順(投稿)を取得
  get 'notes/order_index', to: 'notes#order_index'

  # いいねしてくれたユーザーを表示するためのルーティング
  get 'favorites/user/:id', to: 'favorites#user'

  # コメントした投稿を表示するためのルーティング
  get 'comments/user/:id', to: 'comments#user'

  # いいねした投稿を表示するためのルーティング
  get 'notes/favorite/:id', to: 'notes#favorite'

  # フォローしているユーザー一覧のルーティング
  get 'followings/user/:id', to: 'relationships#followings'

  # フォロワー一覧のルーティング
  get 'followers/user/:id', to: 'relationships#followers'

  # タグがつけられた投稿一覧のルーティング
  get 'tag/:id/notes', to: 'tags#note'

  # ユーザーのメモページへのルーティング
  get 'memos/user/:id', to: 'memos#index'

  # メモ既読機能
  get 'memos/:id', to: 'memos#checked'

  resources :memos, only: %i[create destroy]

  # プロフィール編集ページ
  resources :intros, only: %i[new create edit update]

  # 投稿(いいね・コメント),インクリメンタルサーチ
  resources :notes do
    resources :favorites, only: %i[create destroy]
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
    collection do
      get 'note_search'
    end
  end

  # コメント削除機能のルーティング
  resources :comments, only: [:destroy]

  # フォロー機能のルーティング
  resources :relationships, only: %i[create destroy]

  # 通知機能のルーティング
  resources :notifications, only: %i[index destroy]

  # DM機能のルーティング
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true, unless: :was_attached?

  has_one_attached :image
  belongs_to :user
  belongs_to :note

  def was_attached?
    image.attached?
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :user_id, uniqueness: { scope: :note_id }
end

app/models/intro.rb
class Intro < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user

  validates :content, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/note.rb
class Note < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :text
    validates :plan
  end

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :note_tags, dependent: :destroy
  has_many :tags, through: :note_tags, dependent: :destroy

  # コメントした投稿を取得するための記述
  has_many :commented_users, through: :comments, source: :user

  has_many :favorites, dependent: :destroy

  # いいねした投稿を取得するための記述
  has_many :favorited_users, through: :favorites, source: :user

  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      note_id: id,
      visited_id: user_id,
      action: 'favorite'
    )
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(note_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end

    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、1つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      note_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメント場合は、通知済みとする
    notification.checked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end

  def self.search(search)
    if search != ''
      Note.where('text LIKE(?)', "%#{search}%")
    else
      Note.all
    end
  end
end

app/models/note_tag.rb
class NoteTag < ApplicationRecord
  belongs_to :note
  belongs_to :tag
end

app/models/notification.rb
class Notification < ApplicationRecord
  # 新着順
  default_scope -> { order(created_at: :desc) }

  belongs_to :note, optional: true
  belongs_to :comment, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :note_tags
  has_many :notes, through: :note_tags

  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[twitter facebook]

  with_options presence: true do
    validates :nickname, format: { with: /\A[a-z\d]{4,16}+\z/i, message: 'が4文字以上の半角英数字ではありません' }
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,100}+\z/i, message: 'は8文字以上の半角英数字ではありません' }
  end

  has_one :intro
  has_many :sns_credentials
  has_many :notes
  has_one_attached :image
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :memos
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  # コメントした投稿を取得するための記述
  has_many :commented_notes, through: :comments, source: :note

  # いいねした投稿を取得するための記述
  has_many :favorited_notes, through: :favorites, source: :note

  # follow_idを参照してfollowingモデルにアクセス
  has_many :followings, through: :relationships, source: :follow

  # relationモデルのfollow_idを参照してフォローの逆をするための記述
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'

  # user_idでフォローしてくれているユーザーを取得するための記述
  has_many :followers, through: :reverse_of_relationships, source: :user

  # 自分が作った通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy

  # 自分宛ての通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # SNS認証ログイン
  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', nickname: 'guest') do |user|
      user.password = 'guest4040'
    end
  end

  # 自分をフォローしないようにするため
  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  # フォローを外せるようにする
  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  # フォローしているか判定
  def following?(other_user)
    followings.include?(other_user)
  end

  # フォロー通知
  def create_notification_follow!(current_user)
    temp = Notification.where(['visiter_id = ? and visited_id = ? and action = ?', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/helpers/intros_helper.rb
module IntrosHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_detail.html.erb
<div class="top-right-content">
  <div class="top-user-card">
    <div class="detail-page-user-card">
      <%= link_to user_path(@user.id), class: 'upper-usericon' do %>
        <% if @user.intro.present? %>
          <%= image_tag @user.intro.image, class: "detail-user-page-icon", alt: "ユーザーアイコン" %>
        <% else %>
          <img src="/assets/default.png" class="detail-user-page-icon " alt="ユーザーアイコン" >
        <% end %>
      <% end %>
    </div>
    <div class="detail-page-user-name">
      <% if @user.intro.present? %>
        <div class="detail-user-name">
          <p class="detail-user-firstname"><%= @user.intro.first_name%></p>
          <p class="detail-user-lastname"><%= @user.intro.last_name%></p>
        </div>
      <% else %>
        <div class="detail-user-nickname">
          <%= @user.nickname %>
        </div>
      <% end %>
    </div>
    <div class="user-status">
      <div class="user-status-top">
        <div class="user-status-note">
          <%= link_to '投稿', user_path(@user.id), class: "status" %>
          <span><%= @user.notes.count %></span>
        </div>
        <div class="user-status-fav">
          <%= link_to "いいね", "/favorites/user/#{@user.id}", class: "status" %>
          <span><%= @user.favorites.count %></span>
        </div>
        <div class="user-status-comment">
          <%= link_to "コメント", "/comments/user/#{@user.id}", class: "status" %>
          <span><%= @user.comments.count %></span>
        </div>
      </div>
      <div class="user-status-bottom">
        <div class="user-status-follow">
          <%= link_to 'フォロー', "/followings/user/#{@user.id}", class: "status" %>
          <span><%= @user.followings.count%></span>
        </div>
        <div class="user-status-follower">
          <%= link_to 'フォロワー', "/followers/user/#{@user.id}", class: "status" %>
          <span><%= @user.followers.count %></span>
        </div>
      </div>
    </div>
  </div>
  <div class="detail-page-user-notes">
    <div class="item-list-navi">
      <i class="fas fa-square item-list-squere"></i><b><%= @user.nickname %></b>'s NOTES
    </div>
    <% @user.notes.each do |note| %>
      <li class="my-item-list">
        <div class="my-item-list-content">
          <div class="my-item-list-tag">
            <% note.tags.each do |tag| %>
              <i class="fas fa-tags my-list-tag-img"></i>
              <%= link_to "#{tag.name}", "/tag/#{tag.id}/notes", class: "tag" %>
            <% end %>
          </div>
          <div class="my-item-list-detail">
            <%= link_to note_path(note.id), class: "my_list_note_link" do %>
              <%= note.title%>
            <% end %>
          </div>
        </div>
        <div class="my-item-list-rower">
          <div class="my-item-list-opt">
            <i class="fas fa-book myitem-like-btn"></i><span><%= note.favorites.count %></span>
            <i class="far fa-comment myitem-comment-btn"></i><span><%= note.comments.count %></span>
          </div>
          <div class="my-item-list-created">
            <%= note.created_at.strftime('%Y/%m/%d') %>
          </div>
        </div>
      </li>
    <% end %>
      <div class="my-detail-page-nation">
        <span><%= paginate @notes %></span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer-left">
    <div class="concept">
    <a href="#" class="footer-title">Plans App</a>
    <p class="footer-copy">Tell me your plan.</p>
    <div class="footer-sns">
      <a href="#" class="twitter-link"><i class="fab fa-twitter footer-twitter"></i></a>
      <a href="#" class="facebook-link"><i class="fab fa-facebook-square footer-facebook"></i></a>
    </div>
    <p class="small"><small>@2021 plans.com</small></p>
  </div>
</div>
<div class="footer-right">
  <div class="footer-info">
    <div class="information-left">
      <p class="information"><b>Plans App</b></p>
      <ul class="information-lists">
        <a href="#"><li>About</li></a>
        <a href="#"><li>利用規約</li></a>
        <a href="#"><li>プライバシー</li></a>
        <a href="#"><li>ガイドライン</li></a>
      </ul>
    </div>
    <div class="information-right">
      <p class="information"><b>About</b></p>
      <ul class="information-lists-second">
        <a href="#"><li>お知らせ</li></a>
        <a href="#"><li>ご意見</li></a>
        <a href="#"><li>ヘルプ</li></a>
        <a href="#"><li>広告掲載</li></a>
      </ul>
    </div>
    <div class="example">
      <p class="increments"><b>Increments</b></p>
      <ul class="example-lists">
        <a href="#"><li>About</li></a>
        <a href="#"><li>ブログ</li></a>
        <a href="#"><li>Team</li></a>
        <a href="#"><li>Job</li></a>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_header_links.html.erb
<%= link_to root_path do %>
  <i class="fas fa-home home"></i>
<% end %>
<%= link_to new_note_path, class: "post" do %>
  <i class="fas fa-pen-square"></i>投稿する
<% end %>
<%= link_to notifications_path, class: "upper-notification" do %>
  <i class="far fa-bell"></i>
<% end %>

app/views/shared/_note_header.html.erb
<div class="session-header">
  <%= render 'shared/session_header' %>
  <div class="session-right">
    <%= render 'shared/header_links' %>
    <%= link_to user_path(current_user.id), class: 'upper-usericon' do %>
      <% if current_user.intro.present? %>
        <div class="session-usericon">
        <%= image_tag current_user.intro.image, class: "index-icon", alt: "ユーザーアイコン"%>
        </div> 
      <% else %>
        <div class="session-usericon">
          <img src="/assets/default.png" class="index-icon" alt="ユーザーアイコン">
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_session_header.html.erb
<div class="session-left">
  <%= link_to "Plans App", root_path %>
</div>