config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # マイページ
  resources :users, only: [:show]

  root to: 'notes#index'

  # 新着順(投稿)を取得
  get 'notes/order_index', to: 'notes#order_index'

  # いいねしてくれたユーザーを表示するためのルーティング
  get 'favorites/user/:id', to: 'favorites#user'

  # コメントした投稿を表示するためのルーティング
  get 'comments/user/:id', to: 'comments#user'

  # いいねした投稿を表示するためのルーティング
  get 'notes/favorite/:id', to: 'notes#favorite'

  # フォローしているユーザー一覧のルーティング
  get 'followings/user/:id', to: 'relationships#followings'

  # フォロワー一覧のルーティング
  get 'followers/user/:id', to: 'relationships#followers'

  # タグがつけられた投稿一覧のルーティング
  get 'tag/:id/notes', to: 'tags#note'

  # ユーザーのメモページへのルーティング
  get 'memos/user/:id', to: 'memos#index'

  # メモ既読機能
  get 'memos/:id', to: 'memos#checked'

  resources :memos, only: %i[create destroy]

  # プロフィール編集ページ
  resources :intros, only: %i[new create edit update]

  # 投稿(いいね・コメント),インクリメンタルサーチ
  resources :notes do
    resources :favorites, only: %i[create destroy]
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
    collection do
      get 'note_search'
    end
  end

  # コメント削除機能のルーティング
  resources :comments, only: [:destroy]

  # フォロー機能のルーティング
  resources :relationships, only: %i[create destroy]

  # 通知機能のルーティング
  resources :notifications, only: %i[index destroy]

  # DM機能のルーティング
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show destroy]
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[show destroy]

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    if @room.destroy
      redirect_to root_path
    else
      render action: :show
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/show.html.erb
<div class="chat-wrapper">
  <div class="session-header">
    <% if user_signed_in? %>
      <%= render 'shared/note_header' %>
    <% else %>
      <div class="show-header">  
        <div class="upper-header">
          <div class="upper-left">
            <%= link_to "Plans App", root_path %>
          </div>
          <div class="upper-right">
            <%= link_to "ユーザー登録", new_user_registration_path, class: "upper-regist" %>
            <%= link_to "ログイン", new_user_session_path, class: "upper-session" %>
            <%= link_to 'ゲストログイン（閲覧用）',  users_guest_sigin_in_path, method: :post, class: "guest-session" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="room-title-text">
    <h4 class="rooms-title">チャットルーム</h4>
  </div>
  <div class="room-user-info">
    <% @entries.each do |e| %>
      <div class="room-user-detail">
        <div class="room-user-icon">
          <%= link_to user_path(e.user.id), class: 'upper-usericon' do %>
            <% if e.user.intro.present? %>
              <div class="session-usericon">
                <%= image_tag e.user.intro.image, class: "chat-top-icon", alt: "ユーザーアイコン" %>
              </div> 
            <% else %> 
              <div class="session-usericon">
                <img src="/assets/default.png" class="chat-top-icon" alt="ユーザーアイコン" >
              </div>
            <% end %> 
          <% end %>
        </div>
        <div class="room-user-nickname">
          <a class="rooms-user-link" href="/users/<%= e.user.id %>">
            <b><%= e.user.nickname %></b>さん
          </a>
        </div>
      </div>
    <% end %>
  </div>
  <hr>
  <div class="room-destroy">
    <%= link_to room_path(@room.id), method: :delete, class: "room-delete-link" do %>
      <i class="fas fa-trash-alt room-destroy-icon"></i>チャットを終了する
    <% end %>
  </div>
  <div class="chats">
    <div class="chat">
      <% if @messages.present? %>
        <% @messages.each do |m| %>
          <div class="chat-box">
            <div class="chat-face">
              <%= link_to user_path(m.user.id), class: 'upper-usericon' do %>
                 <% if m.user.intro.present? %>
                  <div class="session-usericon">
                    <%= image_tag m.user.intro.image, class: "chat-icon", alt: "ユーザーアイコン" %>
                  </div> 
                <% else %> 
                  <div class="session-usericon">
                    <img src="/assets/default.png" class="chat-icon" alt="ユーザーアイコン" >
                  </div>
                <% end %> 
              <% end %>
              <%= link_to m.user.nickname, user_path(m.user.id), class:"chat-nickname-link" %>
            </div>
            <div class="chat-messages"> 
              <p class="chat-text"><%= m.text %></p>
            </div>
            <div class="chat-time">
              <%= m.created_at.strftime("%Y-%m-%d %H:%M")%>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="chat-footer">
    <div class="chat-posts">
      <%= form_with model: @message, url: messages_path, local: true do |f| %>
         <%= f.text_field :text, placeholder: "メッセージを入力して下さい" , size: 70, class:"form-chat-field" %>
          <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.submit "投稿",class: 'chat-submit'%>
      <% end %>
    </div>
  </div>
</div>