config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # マイページ
  resources :users, only: [:show]

  root to: 'notes#index'

  # 新着順(投稿)を取得
  get 'notes/order_index', to: 'notes#order_index'

  # いいねしてくれたユーザーを表示するためのルーティング
  get 'favorites/user/:id', to: 'favorites#user'

  # コメントした投稿を表示するためのルーティング
  get 'comments/user/:id', to: 'comments#user'

  # いいねした投稿を表示するためのルーティング
  get 'notes/favorite/:id', to: 'notes#favorite'

  # フォローしているユーザー一覧のルーティング
  get 'followings/user/:id', to: 'relationships#followings'

  # フォロワー一覧のルーティング
  get 'followers/user/:id', to: 'relationships#followers'

  # タグがつけられた投稿一覧のルーティング
  get 'tag/:id/notes', to: 'tags#note'

  # ユーザーのメモページへのルーティング
  get 'memos/user/:id', to: 'memos#index'

  # メモ既読機能
  get 'memos/:id', to: 'memos#checked'

  resources :memos, only: %i[create destroy]

  # プロフィール編集ページ
  resources :intros, only: %i[new create edit update]

  # 投稿(いいね・コメント),インクリメンタルサーチ
  resources :notes do
    resources :favorites, only: %i[create destroy]
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
    collection do
      get 'note_search'
    end
  end

  # コメント削除機能のルーティング
  resources :comments, only: [:destroy]

  # フォロー機能のルーティング
  resources :relationships, only: %i[create destroy]

  # 通知機能のルーティング
  resources :notifications, only: %i[index destroy]

  # DM機能のルーティング
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show destroy]
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user

  validates :content, presence: true
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[index destroy]

  def index
    @memos = Memo.all.order('created_at DESC')
    redirect_to root_path unless current_user.id == @user.id
  end

  def create
    @memo = Memo.new(memo_params)
    if @memo.valid?
      @memo.save
      redirect_to "/memos/user/#{current_user.id}"
    else
      render action: :index
    end
  end

  def destroy
    if current_user.id == @user.id
      Memo.destroy_all
      redirect_to "/memos/user/#{current_user.id}"
    else
      render action: :index
    end
  end

  def checked
    memo = Memo.find(params[:id])
    if memo.checked
      memo.update(checked: false)
    else
      memo.update(checked: true)
    end

    item = Memo.find(params[:id])
    render json: { memo: item }
  end

  private

  def memo_params
    params.permit(:content).merge(user_id: current_user.id)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/index.html.erb
<div class="session-header">
  <% if user_signed_in? %>
    <%= render 'shared/note_header' %>
  <% else %>
    <div class="show-header">  
      <div class="upper-header">
        <div class="upper-left">
           <%= link_to "Plans App", root_path %>
        </div>
        <div class="upper-right">
          <%= link_to "ユーザー登録", new_user_registration_path, class: "upper-regist" %>
          <%= link_to "ログイン", new_user_session_path, class: "upper-session" %>
          <%= link_to 'ゲストログイン（閲覧用）',  users_guest_sigin_in_path, method: :post, class: "guest-session" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="memo-main">
  <div class="memo-user-nickname">
    <span><b><%= @user.nickname%></b>'s Plans</span>
  </div>
  <div class="memo-form">
    <%= form_with url: memos_path, method: :post,id: "form", class: "memo-fields", local: true do |f| %>
      <%= f.text_field :content, id: "content", class: "memo-content-field" %>
      <%= f.submit '追加する' , id: "submit", class: "memo-submit" %>
    <% end %>
  </div>
  <div class="grid">
    <div class="box box1">
      <span>Action To Do</span>
      <% @memos.each do |memo| %>
        <div class="memo" data-id=<%= memo.id %> data-check=<%= memo.checked %>>
          <div class="item" id="item" draggable="true">
            <div class="memo-date">
              追加日時：<%= memo.created_at.strftime('%Y/%m/%d') %>
            </div>
            <div class="memo-content">
              <%= memo.content %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="box box2">
      <span>Cleared Action's</span>
    </div>
  </div>
  <div class="memo-destroy-box">
      <%= link_to memo_path, method: :delete, class: "memo-delete-link" do %>
        <i class="fas fa-trash-alt memo-destroy"></i>一括削除
      <% end %>
    </div>